const readlineSync = require('readline-Sync')
console.log("insira um ano e irei verificar se é bissexto:\n")
let ano = readlineSync.question("-")
ano = parseInt(ano)
if(ano < 1752)
console.log(`qualquer ano antecessor que 1752 nao é bissexto.`)
else if(ano % 4 === 0 && ano % 100 !== 0 || ano % 4 === 0 && ano % 100 === 0 && ano % 400 === 0)
console.log(`o ano ${ano} é bissexto`)
else if(ano % 4 !== 0 || ano % 4 === 0 && ano % 100 === 0 && ano % 400 === 1)
console.log(`o ano ${ano} não é bissexto.`)